### ISSUE TITLE
filter for gluten free options

### ISSUE THREAD

**Issue by r4diosilence** [alexanderwallau/bonn-mensa#12]
**Is your feature request related to a problem? Please describe.**

There is an option to only show vegetarian or vegan options but no way to only show gluten free options.

**Describe the solution you'd like**

Please add an option to only show gluten free options. Gluten is allergen code 40, wheat is allergen code 40a.

**Describe alternatives you've considered**

I've considered --show-all-allergens but that's not a filter and the output is a little cluttered for my purpose.

**Additional context**

not necessary, I think

**Comment by alexanderwallau** [comment]
Implemented in the current development version will be in the new releae when some other features are finished.
Usable with the flag --glutenfree
